{% set name = "ansible-vault" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5ce8fdb5470f1449b76bf07ae2abc56480dad48356ae405c85b686efb64dbd5e

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - ansible
    - python

test:
  requires:
    - ansible
  imports:
    - ansible_vault

about:
  home: https://github.com/tomoh1r/ansible-vault
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: R/W an ansible-vault yaml file
  dev_url: https://github.com/tomoh1r/ansible-vault

extra:
  recipe-maintainers:
    - zoltanctoth
