{% set name = "ansible-vault" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7e985a9329e4728961d7a00f62412fa8ec246a4d832ad6e6d158165e0026529b

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - ansible
    - python

test:
  requires:
    - ansible
  imports:
    - ansible_vault

about:
  home: https://github.com/tomoh1r/ansible-vault
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: R/W an ansible-vault yaml file
  dev_url: https://github.com/tomoh1r/ansible-vault

extra:
  recipe-maintainers:
    - zoltanctoth
